import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         
      >
        <Theme appearance="dark"  accentColor="tomato" grayColor="sand" panelBackground="solid" radius="none" scaling="90%">
        {children}
        
        </Theme>
        
      </body>
    </html>
  );
}

